#1 java-racingcar mission
awesome-backend-java/java-racingcar pull request #1
Opened 2021-03-25 07:18 UTC by jhn5052

## 구현
1. 계산기
2. racing car

### 아쉬운점
- racing car mission. 메소드별 unit test를 제대로 못했고, fail test를 못함
- map말고 treeMap을 썼다면 어땠을까 싶음
- test를 위해 전역변수 -> 파라미터로 모두 전달하는 방식으로 변경(그냥 코드가 맘에 안듦)
- input메소드의 애매함...
- TDD 어렵다

2021-03-29 10:11 UTC, oeeen requested changes
꼼꼼하게 다 보고 리뷰 달지는 못한 것 같아요. 리뷰 요청까지 열심히 해주셔서 감사합니다 👍 
몇가지 제 생각을 남겨두었습니다. 참고해주시고, 궁금한 점 있으시면 언제든 메신저 주세요!

2021-03-29 10:11 UTC, oeeen commented on src/main/java/racingcarApp.java
> +public class racingcarApp {
```suggestion
public class RacingcarApp {
```

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +	public boolean isOp(String op){
```suggestion
	private boolean isOp(String op){
```

내부에서만 사용하는 메서드는 private 으로 해주세요.

2021-03-29 10:11 UTC, oeeen commented on src/main/java/CalApp.java
> +public class CalApp {
```suggestion
public class CalculatorApplication {
```

CalApp 만 보아서는 어떤 프로그램인지 알기 어렵습니다.

2021-03-29 10:11 UTC, oeeen commented on src/main/java/CalApp.java
> +		String calStr = sc.nextLine();
변수명은 축약하지 않는 편이 좋습니다. (물론 실무에서는 과도하게 길다면 축약하여 사용할 수 있겠지만..)
그리고 `String` 이라는 타입이므로 Str이라는 네이밍이 중복됩니다.
```suggestion
		String input = sc.nextLine();
```

2021-03-29 10:11 UTC, oeeen commented on src/main/java/CalApp.java
> +		String[] splitCalStr = calculator.splitStr(calStr);
Calculator 라는 객체가 이름에 맞게 행동한다면 splitStr 메서드는 Calculator라는 객체가 해야하는 행동일까요? splitStr의 ","를 기반으로 split을 해주는 메서드는 util class의 메서드로 빼보는 것도 한 가지 방법입니다.

2021-03-29 10:11 UTC, oeeen commented on src/main/java/CalApp.java
> +		int result = calculator.opNumSplitSave(splitCalStr);
opNumSplitSave 라는 메서드는 이름만으로는 ,로 분리된 String array를 가지고 어떤 일을 하는지 예측하기 어렵습니다. 더 적절한 메서드 명은 없을까요?

Calculator Class에 solve(input) 이라거나, calculate(input) 과 같은 단일 메서드를 만들고 그 메서드 내부에서 계산하는 작업을 하는 건 어떨까요?

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +			.filter(s -> isOp(s))
```suggestion
			.filter(this::isOp)
```

메서드 레퍼런스를 사용할 수 있습니다. `Effective Java, item 43. 람다보다는 메서드 참조를 사용하라` 를 참고하시면 좋습니다.

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +			.map(s -> Integer.parseInt(s))
```suggestion
			.map(Integer::parseInt)
```

ditto

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +	public int solve(List<String> opList, List<Integer> numList){
```suggestion
	public int solve(List<String> operators, List<Integer> numbers){
```

List Type의 변수에 List라는 네이밍은 중복이 아닐까요?

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +	public int sum(int num1, int num2){
계산 하는 메서드들은 내부에서만 사용하는데, public 으로 두신 이유는 테스트 코드에서 사용하기 위해서 일까요?

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +	public int mul(int num1, int num2){
```suggestion
	public int multiply(int num1, int num2){
```

그렇게 길지 않으니 생략하지 말아주세요..ㅠㅠ

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +	public int sub(int num1, int num2){
```suggestion
	public int subtract(int num1, int num2){
```

그렇게 길지 않으니 생략하지 말아주세요..ㅠㅠ

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +	public int div (int num1, int num2) throws ArithmeticException {
```suggestion
	public int divide(int num1, int num2) throws ArithmeticException {
```

2021-03-29 10:11 UTC, oeeen commented on src/main/java/calculator/Calculator.java
> +	public String[] splitStr(String calStr){
```suggestion
	public String[] splitStr(String calStr) {
```

전반적으로 띄어쓰기가 없는데, 코딩 스타일로 정의되어 있는건가요?

2021-03-29 10:11 UTC, oeeen commented on src/test/java/calculatorTest/CalculatorTest.java
> +public class CalculatorTest {
제가 처음에 설명해드릴 때 실패하는 Input 이 없다고 가정하라고 해서 잘못된 input 에 대한 실패 케이스 테스트가 없군요.. 제 잘못입니다.ㅠㅠ

모든 계산 케이스에 대한 테스트 💯

2021-03-29 10:11 UTC, oeeen commented on src/test/java/calculatorTest/CalculatorTest.java
> +	Calculator calculator;
default 접근 제어자를 사용하신 이유가 있나요?

2021-03-29 10:11 UTC, oeeen commented on src/test/java/racingcar/RacingCarTest.java
> +	String[] testRcCars;
default 접근 제어자를 사용하신 이유가 있나요?

2021-03-29 10:11 UTC, oeeen commented on src/main/java/racingcar/RacingCar.java
> +	public String[] splitCars(String carStr){
문자열 계산기와 동일합니다.

2021-03-29 10:11 UTC, oeeen commented on src/main/java/racingcar/RacingCar.java
> +	public int inputRaceNum(String[] racingCars){
메서드 내부에서 racingCars 변수를 전혀 사용하지 않습니다.

2021-03-29 10:11 UTC, oeeen commented on src/main/java/racingcar/RacingCar.java
> +		int racingNum = Integer.parseInt(sc.nextLine());
사용자의 입력이 숫자가 아닌 경우에 Exception이 발생할 것 같네요.

2021-03-29 10:11 UTC, oeeen commented on src/test/java/racingcar/RacingCarTest.java
> +		Map<String, Integer> mapTest = new HashMap<>();
변수명만 보면 map을 테스트하는 변수 같지 않나요?

2021-03-29 10:11 UTC, oeeen commented on src/main/java/racingcar/RacingCar.java
> +	public void randomNum(String[] racingCars, int idx, Map<String, Integer> rcTotal){
메서드 이름은 동사로 시작하는 것이 좋습니다.

2021-03-29 10:11 UTC, oeeen commented on src/main/java/racingcar/RacingCar.java
> +		Map<String, Integer> rcTotal = new HashMap<>();
지금은 이름을 key, 현재 위치는 value로 갖는 map으로 구성하셨는데,

```java
public class Car {
    private String name;
    private int position;
}
```

과 같은 객체를 만들어보면 구조가 어떻게 바뀔까요?

2021-04-04 13:08 UTC, jhn5052 commented
@oeeen 리뷰해주신 것 바탕으로 코드 수정했습니다! 리뷰해주셔서 감사해요😁

2021-04-18 15:59 UTC, oeeen approved these changes
리뷰어가 지식이 부족해서 리뷰가 깔끔하지 못하네요. 죄송합니다..

아쉬운 점은 racing car에 대한 테스트가 좀 부족했고, Random 성을 어떻게 다뤄서 테스트를 해야할까? 에 대한 고민을 못해봤다는 부분이 아쉽네요!

리뷰하면서 더 좋은 리뷰를 하려면 저도 많이 공부해야겠다고 느끼게 되네요.. 👍

2021-04-18 15:59 UTC, oeeen commented on src/test/java/calculatorTest/CalculatorTest.java
> +package calculatorTest;
```suggestion
package calculator;
```

2021-04-18 15:59 UTC, oeeen commented on src/main/java/utils/Utils.java
> +public class Utils {
Utils는 너무 포괄적인 네이밍 아닐까요?

2021-04-18 15:59 UTC, oeeen commented on src/main/java/calculator/OperatorType.java
> +	public static OperatorType getOperatorType(String operator) {
```suggestion
	private static OperatorType getOperatorType(String operator) {
```

2021-04-18 15:59 UTC, oeeen commented on src/main/java/racingcar/RacingCar.java
> +	private void makeRandomNumber(List<Car> cars, int idx) {
makeRandomNumber method는 randomNumber를 만들어 리턴해줄 것 같은 메서드지만, 내부에서 car의 상태를 변화시키네요.(add position)

이를 분리시키기 위해서는 randomNumber를 만들어주는 클래스를 빼는 방법(유틸 클래스)도 가능할 것 같습니다. 그리고 MVC 패턴으로 분리하는 작업을 한다면, Input과 Output을 만들어주는 부분을 View 쪽으로 분리시킬 수 있을 것 같아요.

View를 도메인에서 분리시키면서 RacingCar 객체가 정말로 RacingCar에 대한 역할만을 수행하고 있는지 다시 생각해볼 수 있을 것 같아요.

View 단을 분리한다고 하면 제 개인적인 생각으로는 View에 대한 테스트는 Input에 대한 Validation이 있다면, 그 Validation이 정상적으로 동작하는 지에 대한 테스트, Output은 정해진 input에 따라 output이 똑같이 나오는 지 정도만 테스트하면 된다라고 생각해요.

또 한가지 생각해볼 것은 RandomNumber를 받아서 Racing을 하는데, 이 Random 성 때문에 테스트가 어렵다라고 생각할 수 있어요. 그러면 이 Random 이 되는 부분을 어떻게 분리시킬 수 있을까? 라는 생각을 해볼 수도 있을 것 같아요.

2021-04-18 15:59 UTC, oeeen commented on src/test/java/racingcar/RacingCarTest.java
> +class RacingCarTest {
테스트가 좀 부족한 것 같네요. RacingCar 객체 내에 private void 형태의 메서드들이 여러 작업들을 수행하고 있어서 테스트가 쉽지 않을 것 같네요. 다음 미션에서는 일단 모든 public method에 대한 테스트를 작성해보는 방향으로 가보는 건 어떨까요?

2021-04-18 15:59 UTC, oeeen commented on src/main/java/racingcar/RacingCar.java
> +	public List<String> selectWinner(List<Car> cars) {
stream 사용 👍

2021-04-18 16:00 UTC, merged